Bump to Node 12 for FIPS compliance
SAP/fundamental-react pull request #1227
Opened 2020-09-29 20:26 UTC by dmatis

### Description
Bumps to Node 12.18.4 to maintain FIPS compliance

2020-09-29 20:42 UTC, jbadan requested changes
It looks like we need to run `npm i` here - Error from the deploy log in netlify - https://app.netlify.com/sites/fundamental-react/deploys/5f739891da82720008cf58b1

```
1:32:28 PM: ERR! Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
1:32:28 PM: ERR! Error: Missing binding /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
1:32:28 PM: ERR! Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
1:32:28 PM: ERR!
1:32:28 PM: ERR! Found bindings for the following environments:
1:32:28 PM: ERR!   - Linux 64-bit with Node.js 10.x
1:32:28 PM: ERR!
1:32:28 PM: ERR! This usually happens because your environment has changed since running `npm install`.
1:32:28 PM: ERR! Run `npm rebuild node-sass` to download the binding for your current environment.
```

2020-09-29 20:45 UTC, dmatis commented
@jbadan I ran `npm rebuild node-sass`:
```
 ~/coreui/fundamental-react   bump-node-12  npm rebuild node-sass

> node-sass@4.14.1 install /Users/i858692/coreui/fundamental-react/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /Users/i858692/coreui/fundamental-react/node_modules/node-sass/vendor/darwin-x64-72/binding.node

> node-sass@4.14.1 postinstall /Users/i858692/coreui/fundamental-react/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/i858692/coreui/fundamental-react/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Testing binary
Binary is fine
node-sass@4.14.1 /Users/i858692/coreui/fundamental-react/node_modules/node-sass
```
And `npm install`:
```
 ~/coreui/fundamental-react   bump-node-12  npm install
npm WARN @egoist/vue-to-react@1.1.0 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.
npm WARN axe-puppeteer@1.1.0 requires a peer of puppeteer@^1.10.0 || ^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-puppeteer@4.4.0 requires a peer of puppeteer@>= 1.5.0 < 3 but none is installed. You must install peer dependencies yourself.
npm WARN react-docgen-typescript@1.16.5 requires a peer of typescript@>= 3.x but none is installed. You must install peer dependencies yourself.
npm WARN react-docgen-typescript-loader@3.7.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@16.13.1 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.

(node:16639) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
audited 3537 packages in 11.585s

191 packages are looking for funding
  run `npm fund` for details

found 7888 vulnerabilities (7871 low, 17 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
However, there are no changes to commit, 😕

2020-09-29 21:16 UTC, prsdthkr approved these changes

2020-09-29 21:38 UTC, jbadan approved these changes

2020-10-05 13:35 UTC, jbadan commented
@dmatis Did you want to merge this?

2020-10-05 23:10 UTC, merged